### ISSUE TITLE
© character in LICENSE.md is rendered as &copy;

### ISSUE THREAD

**Issue by joshfriend** [jacebrowning/template-python#116]

**Comment by jacebrowning** [comment]
In what situations?

See the correct character in my browser on:

- https://github.com/jacebrowning/template-python-demo/blob/python3-pytest/LICENSE.md
- http://jacebrowning.github.io/template-python-demo/about/license/

**Comment by joshfriend** [comment]
[look at the `git blame`](https://github.com/jacebrowning/template-python-demo/blame/python3-pytest/LICENSE.md#L5) for that file. I guess I was expecting to see the actual character in the file.

**Comment by jacebrowning** [comment]
Yeah, `&copy;` is the actual file contents which gets rendered as ©.

**Comment by jacebrowning** [comment]
Unless this is causing other problems `&copy;` is probably safer (no encoding) when rendering and converting this file.
