### ISSUE TITLE
Upload to PyPI via Warehouse for a less broken experience

### ISSUE THREAD

**Issue by joshfriend** [jacebrowning/template-python#125]
https://mail.python.org/pipermail/distutils-sig/2016-June/029083.html

**Comment by jacebrowning** [comment]
How would this be done for the template, an option to the `setup.py` call?

**Comment by joshfriend** [comment]
It may be as simple as changing the url passed to the `--repository` flag of `setup.py` to point to https://upload.pypi.io/legacy/
