### ISSUE TITLE
Unable to rebuild the documentation

### ISSUE THREAD

**Issue by grandrew** [jacebrowning/template-python#166]
`make doc` does nothing after first run
and
`make clean-doc` is not available

p.s. would be nice to have some auto-doc/readthedocs integration too

**Comment by jacebrowning** [comment]
What do you mean by "does nothing"?

`mkdocs` _shouldn't_ need to be "cleaned", but I could see a `clean-doc` command being added.

FWIW, a project using this template _can_ be hooked up to ReadTheDocs with no extra tooling. See http://sappy.readthedocs.io/ for an example. Is there something else you're looking for?

**Comment by jacebrowning** [comment]
The `pandoc` system dependency is considered optional, but is listed in the generated `CONTRIBUTING.md`: https://github.com/grandrew/taskjuggler-python/blob/ec954c1f4a8b8ae8073484c7462aacc27a9639da/CONTRIBUTING.md

**Comment by jacebrowning** [comment]
Also, if you run `$ make doctor` in your project it will tell you that you need `pandoc` installed to generated the README for PyPI.

Let me know if you think any more can be done to improve this.
