### ISSUE TITLE
Pipfile dependencies are not included in setuptools config automatically

### ISSUE THREAD

**Issue by grandrew** [jacebrowning/template-python#167]
I had to manually move the requirements from `Pipfile` to setup.py in order for the `make dist` and `make upload` to actually have the dependencies set in the egg
see https://github.com/grandrew/taskjuggler-python

**Comment by jacebrowning** [comment]
`Pipfile` and `setup.py` serve two different audiences. For a **library** (which is what this template generates), `Pipfile` identifies the dependencies needed to work on the project while `setup.py` identifies the dependencies your end users will need to install.

The version specification in `setup.py` should be as broad as your library will support, while you might chose to develop against specific versions in `Pipfile` or remove the `[packages]` section altogether.

Additional reading: https://github.com/pypa/pipfile/issues/27
