### ISSUE TITLE
[Feature Request] Support for Gitlab

### ISSUE THREAD

**Issue by e0lithic** [jacebrowning/template-python#191]
Hi,

First of all great work. I am just starting out with python and devops tooling and this is indeed one of the best python templates for packages out there to learn best practices and development in general. Would it be possible to extend support for gitlab and gitlab CI.

Thanks

**Comment by jacebrowning** [comment]
I'd be happy to review a PR that adds a `.gitlab-ci.yml` that maps the CI concepts from [`.travis.yml`](https://github.com/jacebrowning/template-python/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/.travis.yml).

**Comment by e0lithic** [comment]
Sure will do it soon.
