### ISSUE TITLE
github action fails if poetry.lock isn't commited

### ISSUE THREAD

**Issue by russkel** [jacebrowning/template-python#202]
I get the following error on the github CI when I have no poetry.lock file:

```
Run make install
make: *** No rule to make target 'poetry.lock', needed by '.venv/.poetry-1bb2349c6b08c33bffaaa07662f9dd252be7f5b8'.  Stop.
Error: Process completed with exit code 2.
```

However maybe it should take into consideration that Poetry can install deps fine without it:
https://python-poetry.org/docs/basic-usage/#installing-without-poetrylock

In addition, the `Run Gr1N/setup-poetry@v4` stage warns of a deprecated installer. I changed it to `v7` and that sorted out that warning.

**Comment by jacebrowning** [comment]
> I get the following error on the github CI when I have no poetry.lock file

This template expects that `poetry.lock` be part of your repository. Run `poetry lock` if you need to generate one. I've updated the `README.md` to reflect that all generated files should be committed.

> In addition, the Run Gr1N/setup-poetry@v4 stage warns of a deprecated installer. I changed it to v7 and that sorted out that warning.

Thanks! I've updated the template to reflect that.

**Comment by russkel** [comment]
Alright. Thanks.
