### ISSUE TITLE
Add sphinx docs generation

### ISSUE THREAD

**Issue by joshfriend** [jacebrowning/template-python#43]
Use a process compatible with the [RTD build process](https://read-the-docs.readthedocs.org/en/latest/builds.html).

**Comment by jacebrowning** [comment]
Another good example from PyOhio 2015: https://github.com/tylerdave/cookiecutter-python-package/tree/master/%7B%7Bcookiecutter.repo_name%7D%7D/docs

**Comment by jacebrowning** [comment]
For most things I make `mkdocs` works fine and is easier to work with.

`mkdocs` is already built into the template and produces pages like this: http://gitman.readthedocs.io/
