### ISSUE TITLE
Consider removing coverage requirement

### ISSUE THREAD

**Issue by joshfriend** [jacebrowning/template-python#71]
Coveralls supports setting a minimum coverage percentage. If the threshold is not met, it will post a failing status to the GitHub Status API for that pull request. Using this instead of the current setup would let the coverage check fail the pull request checks separately from unit tests run by travis.

![](http://i.imgur.com/S0RpL4g.png)

**Comment by jacebrowning** [comment]
Can you think of any way to determine, locally, if coverage has dropped? Otherwise, I agree that it's probably time to remove this.

**Comment by joshfriend** [comment]
this works:

```makefile
.PHONY: test-pytest
test-pytest: depends-ci .clean-test
	$(COVERAGE) run --source $(PACKAGE) --module py.test $(PACKAGE) --doctest-modules
	$(COVERAGE) html --directory .coverage-html
	@if [ "$(TRAVIS)" ]; then                                                 \
		$(COVERAGE) report --show-missing;                                    \
	else                                                                      \
		$(COVERAGE) report --show-missing --fail-under=$(UNIT_TEST_COVERAGE); \
	fi;
```

**Comment by jacebrowning** [comment]
That could be a good "halfway point". I'll experiment this weekend.
