### ISSUE TITLE
Consider removing UML generator tasks

### ISSUE THREAD

**Issue by joshfriend** [jacebrowning/template-python#76]
I've not seen a case where they would be helpful.

**Comment by jacebrowning** [comment]
I often like to view the import hierarchy to make sure I'm not directly or indirectly causing a circular import.

**Comment by jacebrowning** [comment]
I actually just used this a bunch today to see what kinds of weird import dependencies I was creating to get `flask` routes to work. I'm going to close this unless you have a better way to visualize this.

It might be cool if these graphs could be incorporated into some generate doc pages...
