### ISSUE TITLE
Consider removing .PHONY from targets that are obvious

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/template-python#80]
`pep8`, `pylint`, etc. are **obviously** not going to be confused with actual files/directories. Perhaps `.PHONY` should only be used when necessary (thus keeping the `Makefile` cleaner)?

**Comment by jacebrowning** [comment]
@joshfriend Care to comment?

**Comment by joshfriend** [comment]
> The implicit rule search (see Implicit Rules) is skipped for .PHONY targets. This is why declaring a target as .PHONY is good for performance, even if you are not worried about the actual file existing.

([source](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html))

Though you could just:

```Makefile
.PHONY: pep8 pylint etc
```

instead of marking each one separately.

**Comment by jacebrowning** [comment]
Thanks for looking that up! I'll just leave it the way it is.
