### ISSUE TITLE
Research the arguments for/against tests in the package

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/template-python#81]
Currently, the template suggests putting the tests in the package, but I'd like to remember the main arguments.

The first I can think of is that if you have doctests you can simply run your entire package through your test runner.

**Comment by jacebrowning** [comment]
Potentially `<root>/<package>/test(s)` should be unit tests and `<root>/test(s)`.

**Comment by joshfriend** [comment]
I like `tests/` outside the package folder:

* Speeds up collection time since your module files aren't being scanned for `Test*` classes or functions.
* Helps `setup.py` not get confused or include extra junk when running `find_packages`.

So why not do:

```
repo/
    package/
    tests/
        unit/
        integration/
```

**Comment by jacebrowning** [comment]
What about my doctests comment? Is that **3rd** type of test?

**Comment by jacebrowning** [comment]
Also, one of the advantages of having a root tests directory is that modules horizontally line up with their tests (having unit and integration directories breaks that).
