### ISSUE TITLE
is there a way to update an existing project made with this template to include the newest revisions?

### ISSUE THREAD

**Issue by KyleChamberlin** [jacebrowning/template-python#88]
I have created a number of projects from this python template and I would like them to benefit from the recent improvements to this template... is there an easy way to update the project structure for one of those projects from this newer template?

**Comment by jacebrowning** [comment]
I've looked for the same thing myself. The question is actually more general to [cookiecutter](https://github.com/audreyr/cookiecutter) itself:

> How do I "reapply" an updated template?

The best I have come up with so far:

0. get your project's working tree to a clean state
0. change to the parent directory of your project
0. run `$ cookiecutter gh:jacebrowning/template-python` using the same options as the project you'd like to update (specifically, `project_name` needs to be the name of your project's directory)
0. open your project's working tree in a VCS viewer such as [SourceTree](https://www.sourcetreeapp.com/)
0. discard all undesired changes and sample files
0. ensure your project still works with `$ make doc`, `$ make ci`, etc.
0. commit your re-templated project

**Comment by jacebrowning** [comment]
I created an `update` branch to make this a bit easier: https://github.com/jacebrowning/template-python/blob/master/README.md#apply-updates

**Comment by jacebrowning** [comment]
@KyleChamberlin Lately, I've been using this (new) approach: https://github.com/jacebrowning/template-python#manual-diff
